Importing Packages

In [2]:
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn import metrics
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
# from sklearn.preprocessing  import StandardScaler
import matplotlib.pyplot as plt
import seaborn as sns; sns.set(font_scale=1.2)

Reading page-blocks.data into a dataframe

In [3]:
df = pd.read_csv('page-blocks.data', header = None, delim_whitespace=True)
df.columns = ['Height', 'Length', 'Area', 'Eccen', 'p_black', 'p_and', 'mean_tr', 'blackpix', 'blackand', 'wb_trans', 'Type']
df

,Height,Length,Area,Eccen,p_black,p_and,mean_tr,blackpix,blackand,wb_trans,class
0,5,7,35,1.400,0.400,0.657,2.33,14,23,6,1
1,6,7,42,1.167,0.429,0.881,3.60,18,37,5,1
2,6,18,108,3.000,0.287,0.741,4.43,31,80,7,1
3,5,7,35,1.400,0.371,0.743,4.33,13,26,3,1
4,6,3,18,0.500,0.500,0.944,2.25,9,17,4,1
...,...,...,...,...,...,...,...,...,...,...,...
5468,4,524,2096,131.000,0.542,0.603,40.57,1136,1264,28,2
5469,7,4,28,0.571,0.714,0.929,10.00,20,26,2,1
5470,6,95,570,15.833,0.300,0.911,1.64,171,519,104,1
5471,7,41,287,5.857,0.213,0.801,1.36,61,230,45,1
5472,8,1,8,0.125,1.000,1.000,8.00,8,8,1,4

Separating our data into features and classification

In [9]:
features = df.iloc[:, :-1]
target = df.iloc[:, 10]